Removed unicode decoding
     * merged with master
     * Removed unicode decoding because it breaks
    	on some of the lines in the log files.
    	decodeURI doesn't work on them

    	Try in your browser the following:

    	  decodeURI("http://ru.wikipedia.org/wiki/%D1%F2%EE%EB%EE%ED%E0%F7%E0%EB%FC%ED%E8%EA")
    	  URIError: URI malformed

    	The link mentioned above was found in one of the .gz files on
    	stat1.

    	An earlier discussion on 01-10-2012 (DMY) took place on the
    	channel but I was not able to find a solution.

    	Somehow mediawiki knows how to deal with this URI but I need to do
    	further inspection to see how it does it (regular unicode decoding
    								does not seem enough).

    Change-Id: I9a18e69e553bec42e57db7f2f3cd07229a5dbff6

Change-Id: I1d93a61d1b79249acdf2314f413e35798be0b569